#!/bin/bash

# Update the system
sudo dnf update -y

# Install Apache
sudo dnf install -y httpd mod_ssl
sudo systemctl start httpd
sudo systemctl enable httpd

sudo firewall-cmd --permanent --add-service=http
sudo firewall-cmd --permanent --add-service=https
sudo firewall-cmd --reload

sudo systemctl status httpd